### PR TITLE
Add missing exit to build script

### LINKED ISSUE #67: CI test incorrectly reports success when there's a failure.
See https://travis-ci.org/jaegertracing/cpp-client/jobs/355469697

### PR DESCRIPTION
**Pull request by isaachier**
@rnburn should resolve #67.

### CODE REVIEW

**Comment by rnburn** [comment]
I'd recommend [set -e](https://stackoverflow.com/questions/19622198/what-does-set-e-mean-in-a-bash-script).

**Comment by isaachier** [comment]
@rnburn is this ready?

**Comment by rnburn** [comment]
Yes, LGTM.

**Comment by isaachier** [comment]
Thanks.

**Pull request merged**
