### PR TITLE
Update Hunter to get newest OpenTracing API

### PR DESCRIPTION
**Pull request by isaachier**
Signed-off-by: Isaac Hier <ihier@uber.com>

### CODE REVIEW

**Comment by isaachier** [comment]
@rnburn please take a quick look at the update to Hunter for newest OpenTracing API.

**Comment by isaachier** [comment]
Hunter is a package distribution for lack of a better term. Sort of like updating `apt-get` to get the newest package listings on an Ubuntu/Debian machine, using the latest Hunter release pulls any updates 
to default versions. The related work updating Hunter is here: https://github.com/ruslo/hunter/pull/1369.

**Comment by yurishkuro** [comment]
I see - kind of like brew.

**Comment by isaachier** [comment]
Yes very similar.

**Comment by rnburn** [comment]
👍

**Pull request merged**
