### PR TITLE
Don't use forwarding reference.

### PR DESCRIPTION
**Pull request by rnburn**
If you use the signature
```
template <typename ValueType, typename KeyType, typename DefaultValueType>
ValueType findOrDefault(const YAML::Node& node,
                        KeyType&& key,
                        DefaultValueType&& defaultValue)
```
then 
```
bool val = false;
auto t = findOrDefault(yaml, "key", val);
```
will deduce `DefaultValueType` as `bool&` which is probably not what you want.

### CODE REVIEW

**Comment by isaachier** [comment]
Makes sense to me. Someone else needs to approve this for now. @black-adder?

**Comment by yurishkuro** [comment]
@isaachier could you please add code coverage integration for this repo? Eg with codecov

**Comment by isaachier** [comment]
I have codecov but only on my fork. Will see what I can do here.

**Comment by isaachier** [comment]
See https://codecov.io/gh/jaegertracing/cpp-client. I think we need a hook in the project which I don't have the permissions to add myself.

**Comment by yurishkuro** [comment]
the settings in the repo say
```
Codecov uses GitHub Webhooks to keep in sync with your project.

A webhook has enabled through GitHub Integrations. No setup required.
```

**Comment by isaachier** [comment]
It might report coverage but IDK about the pull request integration.

**Comment by isaachier** [comment]
The pull request would show coverage if the coverage upload had not failed. See the Travis build for details (gcc 6). @rnburn could you please try rebasing this on the most recent release and uploading again so we could see coverage changes?

**Comment by yurishkuro** [comment]
maybe we can remove and re-add the repo to codecov? Don't know why it's not posting.

https://codecov.io/gh/jaegertracing/jaeger-client-java/settings

**Comment by isaachier** [comment]
@yurishkuro let me clarify my point with a copy of the failure log:

```
[0K$ bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-d109cc7


[0;90m==>[0m Travis CI detected.
    [0;90mproject root:[0m .
    [0;90mYaml found at:[0m codecov.yml
[0;90m==>[0m Running gcov in . [0;90m(disable via -X gcov)[0m
[0;90m==>[0m Python coveragepy not found
[0;90m==>[0m Searching for coverage reports in:
    [0;32m+[0m .
[0;31m-->[0m No coverage report found.
    Please visit [0;36mhttp://docs.codecov.io/docs/supported-languages[0m
```

**Comment by isaachier** [comment]
I'm not sure why the build failed to generate coverage reports, but the whole thing can be found here: https://travis-ci.org/jaegertracing/cpp-client/jobs/302708054. If we trigger another build, ideally on top of newest master, we should see coverage info.

**Comment by isaachier** [comment]
Actually found the coverage issue and working on it now.

**Comment by isaachier** [comment]
@rnburn just added a fix for coverage. If you have a chance please merge from master and push to this branch again so we can see the coverage changes.

**Comment by rnburn** [comment]
done.

**Pull request merged**
